use my arduino install with new cache

diff --git a/.github/workflows/arduino.yml b/.github/workflows/arduino.yml
--- a/.github/workflows/arduino.yml
+++ b/.github/workflows/arduino.yml
@@ -92,8 +92,9 @@ env:
 
 jobs:
 
-  # Prepare and cache install
+  #--------------------------- Prepare and cache install ----------------------------------------------------
   prepare-cache:
+  #----------------------------------------------------------------------------------------------------------
     name: Prepare Arduino cache
     runs-on: ubuntu-latest
     outputs:
@@ -105,25 +106,88 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
+      # Arduino CLI
       - name: Install Arduino CLI
-        uses: arduino/setup-arduino-cli@v2
-        with:
-          version: "1.x"
+        run: |
+          # Script to fetch and run install.sh from arduino/arduino-cli
 
-      - name: Configure Arduino CLI and preinstall platforms
+          # The install script will test to see if the recently installed apps in the path
+          # So set it up in advance:
+          mkdir -p "${PWD}/bin"
+          echo "${PWD}/bin" >> $GITHUB_PATH
+
+          # Sets the install directory to a consistent path at the repo root.
+          ROOT_BIN="$GITHUB_WORKSPACE/bin"
+
+          # Ensures that BINDIR exists before the installer runs
+          mkdir -p "$ROOT_BIN"
+
+          # Save as a global environment variable
+          echo "$ROOT_BIN" >> "$GITHUB_PATH"
+
+          # Download and run install script from Arduino:
+          # -S show errors; -L follow redirects; -v Verbose
+          set +e                 # don't abort on error
+          set -o pipefail
+
+          curl -vSL --retry 5 --retry-delay 10 \
+             https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh  \
+             | sh -x
+          rc=$?
+          c_rc=${PIPESTATUS[0]}  # curl's exit code
+          s_rc=${PIPESTATUS[1]}  # sh's  exit code
+
+          set -e                 # restore default abort-on-error
+
+          # If there was a curl error, we have our own local copy that is more reliable and can add our own debugging
+          if [ "$rc" -ne 0 ]; then
+            echo "Primary install failed: curl=$c_rc, sh=$s_rc. Falling back..." >&2
+            echo "Using local copy of arduino_install.sh"
+            pushd ./Arduino/sketches
+              chmod +x ./arduino_install.sh
+
+              # Mimic curl install, does not use current directory:
+              BINDIR="$ROOT_BIN" sh -x ./arduino_install.sh
+            popd
+          else
+            echo "Alternative install script not needed."
+          fi
+
+      - name: Confirm Arduino CLI install
+        run: arduino-cli version
+
+      - name: Setup Arduino CLI
         run: |
           arduino-cli config init
-          arduino-cli config set build_cache.path "$ARDUINO_BUILD_CACHE"
-          while IFS= read -r url; do
-            [ -n "$url" ] && arduino-cli config add board_manager.additional_urls "$url"
-          done <<EOF
-          $ADDITIONAL_URLS
-          EOF
+
+          # wait 10 minutes for big downloads (or use 0 for no limit)
+          arduino-cli config set network.connection_timeout 600s
+
+          arduino-cli config add board_manager.additional_urls https://www.pjrc.com/teensy/package_teensy_index.json
+          arduino-cli config add board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
           arduino-cli core update-index
-          names=$(echo "${PLATFORMS}" | grep -E 'name:' | awk -F\" '{print $2}')
-          for p in $names; do
-            arduino-cli core install "$p"
-          done
+
+          # mbed nano not yet tested
+          # sudo "/home/$USER/.arduino15/packages/arduino/hardware/mbed_nano/4.2.4/post_install.sh"
+
+          # Install upported boards:
+          arduino-cli core install esp32:esp32            # ESP32
+          arduino-cli core install esp8266:esp8266        # ESP8266
+
+          arduino-cli core install teensy:avr             # PJRC Teensy
+
+          arduino-cli core install arduino:avr            # Arduino Uno, Mega, Nano
+          arduino-cli core install arduino:sam            # Arduino Due
+          arduino-cli core install arduino:samd           # Arduino Zero
+          arduino-cli core install arduino:mbed_nano      # nanorp2040connect
+          arduino-cli core install arduino:mbed_portenta  # portenta_h7_m7
+          arduino-cli core install arduino:mbed_edge
+          arduino-cli core install arduino:renesas_uno
+
+          arduino-cli lib install "ArduinoJson"           # Example dependency
+          arduino-cli lib install "WiFiNINA"              # ARDUINO_SAMD_NANO_33_IOT
+          arduino-cli lib install "Ethernet"              # Install Ethernet library
+          arduino-cli lib install "Bridge"                # Pseudo-network for things like arduino:samd:tian
 
       - name: Ensure ARDUINO_ROOT exists
         run: |
@@ -192,7 +256,6 @@ jobs:
       # Get the SHA value of the latest version of wolfSSL for cache
       - name: Get wolfSSL commit
         id: wolfsha
-        if: steps.restore-wolfssl.outputs.cache-hit != 'true'
         run: echo "sha=$(git -C wolfssl rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
 
       # Attempt to restore the Arduino wolfssl library
@@ -263,7 +326,9 @@ jobs:
             ${{ env.ARDUINO_BUILD_CACHE }}
           key: arduino-${{ runner.os }}-${{ hashFiles('.ci/arduino-cores.lock', '.ci/arduino-libs.lock') }}
 
+  #----------------------------------------------------------------------------------------------------------
   build:
+  #----------------------------------------------------------------------------------------------------------
     name: Latest Compile (${{ matrix.fqbn }})
 #    if: github.repository_owner == 'wolfssl'
     needs: prepare-cache
@@ -311,13 +376,10 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: Install Arduino CLI
-        uses: arduino/setup-arduino-cli@v2
-        with:
-          version: "1.x"
-
-      - name: Confirm Arduino CLI install
-        run: arduino-cli version
+      - name: Ensure ARDUINO_ROOT exists
+        run: |
+          echo "ARDUINO_ROOT=$HOME/Arduino/libraries" >> "$GITHUB_ENV"
+          mkdir -p "$HOME/Arduino/libraries"
 
       - name: Restore Arduino caches
         uses: actions/cache/restore@v4
@@ -330,6 +392,19 @@ jobs:
           restore-keys: |
             arduino-${{ runner.os }}-
 
+      - name: Install only needed core
+        run: |
+            CORE_ID="$(echo "${{ matrix.fqbn }}" | awk -F: '{print $1 ":" $2}')"
+            arduino-cli core install "$CORE_ID"
+
+      - name: Restore cached wolfSSL library
+        uses: actions/cache/restore@v4
+        with:
+          path: ${{ env.ARDUINO_ROOT }}/wolfssl
+          key: wolfssl-lib-${{ runner.os }}-${{ needs.prepare-cache.outputs.wolfsha }}-${{ hashFiles('wolfssl/IDE/ARDUINO/wolfssl-arduino.sh') }}-${{ hashFiles('Arduino/sketches/**') }}
+          restore-keys: |
+              wolfssl-lib-${{ runner.os }}-
+
       - name: Set job environment variables
         run: |
           # Script to assign some common environment variables after everything is installed
@@ -337,8 +412,8 @@ jobs:
           ICON_OK=$(printf "\xE2\x9C\x85")
           ICON_FAIL=$(printf "\xE2\x9D\x8C")
 
-          echo "GITHUB_WORK=$(realpath           "$GITHUB_WORKSPACE/../..")"  >> "$GITHUB_ENV"
-          echo "ARDUINO_ROOT=$(realpath          "$HOME/Arduino/libraries")"  >> "$GITHUB_ENV"
+          echo "GITHUB_WORK=$(realpath $GITHUB_WORKSPACE/../..)" >> "$GITHUB_ENV"
+          echo "ARDUINO_ROOT=$(realpath $HOME/Arduino/libraries)" >> "$GITHUB_ENV"
 
           # Show repo-specific location of examples:
           echo "WOLFSSL_EXAMPLES_ROOT=$(realpath "./Arduino/sketches")"       >> "$GITHUB_ENV"
